#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListaPesama_SignalRClient.Resource", IsApplication=true)]

namespace ListaPesama_SignalRClient
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int btnCancel = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int btnClearSelectedList = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int btnDelete = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int btnOpenFile = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int btnSave = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int etArtist = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int etGenre = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int etOrder = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int etSearch = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int etServerName = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int etTitle = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fragmentContainer = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int lvSelectedSongs = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int lvSongs = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int menu_addSong = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int menu_exit = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int menu_openPreferences = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int tvArtist = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int tvGenre = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int tvOrder = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int tvServerName = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int tvTitle = 2130837525;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int AllSongsList = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Preferences = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int SelectedSongsList = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int SongDetails = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040000
			public const int option_menu = 2130968576;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int addsong = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int cancel = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int cannotConnectToServer = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int clearSelectedList = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int delete = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int emptyServerName = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int exit = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int findSong = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int openFile = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int openPreferences = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int save = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int serverName = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int songArtist = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int songGenre = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int songOrder = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int songTitle = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int successfullyAddedSong = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
